apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 70
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: django_app:latest
            imagePullPolicy: IfNotPresent
            command:
              - python
              - manage.py
              - clearsessions
            envFrom:
              - secretRef:
                  name: django-secrets
            ports:
              - containerPort: 80
          restartPolicy: OnFailure