apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app.kubernetes.io/name: django_app
    app.kubernetes.io/component: web
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 80
  type: ClusterIP